# Site settings
title: "From Angular to Blazor: Building a Front-end Without Javascript"
email: ew@atuw.org
description: "A blog about Blazor"
baseurl: ""
url: "http://ericwisted.com/"
title_description: >- # this means to ignore newlines until "e_image:"
  A blog that documents my transition from building web front-ends in Angular to Microsoft's
  new Blazor framework. As Blazor is still very early in its life-cycle, there's still not
  much documentation on it. Hopefully my stuggle can help other developers with the transition.
title_image: "https://www.gravatar.com/avatar/00000000000000000000000000000000?s=500&d=mm"
google_analytics: "UA-138076088-1"
disqus_account: ericwisted
github_repository: https://github.com/ewisted/ewisted.github.io
addthis_id: ra-5cadadf6d320e63a
post_limit: 5

# Social usernames/URLs
twitter_username: ewisted
github_username:  ewisted
instagram_username: 
reddit_username: 
linkedin_link: https://www.linkedin.com/in/ericwisted/
google_plus_link:
stackoverflow_link: https://stackoverflow.com/users/11297421/atuw
xing_link:
facebook_link:

# Footer
footer_left: #"Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: #"&lt;/&gt; on <a href=\"https://github.com/jacobtomlinson/carte-noire\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: pretty
exclude: [vendor]
